// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 4zPHP3zU1Ca1TqdcDSsn1v
// Component: GMc9FjfgYiA_
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_blank_project.module.css"; // plasmic-import: 4zPHP3zU1Ca1TqdcDSsn1v/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: GMc9FjfgYiA_/css
import Rectangle13Icon from "./icons/PlasmicIcon__Rectangle13"; // plasmic-import: RyRbDqAxe8/icon
import Star1Icon from "./icons/PlasmicIcon__Star1"; // plasmic-import: lc83DJ3-i9/icon
import Ellipse6Icon from "./icons/PlasmicIcon__Ellipse6"; // plasmic-import: 7-xyAG55R7/icon
import airbnb13XfvUa0Ouk from "./images/airbnb1.svg"; // plasmic-import: 3XfvUA0Ouk/picture

export const PlasmicHomepage__VariantProps = new Array();

export const PlasmicHomepage__ArgProps = new Array();

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());

const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicHomepage__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        {true ? (
          <div
            data-plasmic-name={"root"}
            data-plasmic-override={overrides.root}
            data-plasmic-root={true}
            data-plasmic-for-node={forNode}
            className={classNames(
              projectcss.all,
              projectcss.root_reset,
              projectcss.plasmic_default_styles,
              projectcss.plasmic_mixins,
              sty.root
            )}
          >
            <div
              data-plasmic-name={"airBnbExperiences"}
              data-plasmic-override={overrides.airBnbExperiences}
              className={classNames(projectcss.all, sty.airBnbExperiences)}
            >
              <div
                data-plasmic-name={"group77"}
                data-plasmic-override={overrides.group77}
                className={classNames(projectcss.all, sty.group77)}
              >
                <div
                  data-plasmic-name={"image28"}
                  data-plasmic-override={overrides.image28}
                  className={classNames(projectcss.all, sty.image28)}
                />

                <div
                  data-plasmic-name={"image29"}
                  data-plasmic-override={overrides.image29}
                  className={classNames(projectcss.all, sty.image29)}
                />

                <div
                  data-plasmic-name={"image25"}
                  data-plasmic-override={overrides.image25}
                  className={classNames(projectcss.all, sty.image25)}
                />

                <div
                  data-plasmic-name={"image22"}
                  data-plasmic-override={overrides.image22}
                  className={classNames(projectcss.all, sty.image22)}
                />

                <div
                  data-plasmic-name={"image23"}
                  data-plasmic-override={overrides.image23}
                  className={classNames(projectcss.all, sty.image23)}
                />

                <div
                  data-plasmic-name={"image24"}
                  data-plasmic-override={overrides.image24}
                  className={classNames(projectcss.all, sty.image24)}
                />

                <div
                  data-plasmic-name={"image27"}
                  data-plasmic-override={overrides.image27}
                  className={classNames(projectcss.all, sty.image27)}
                />

                <div
                  data-plasmic-name={"image26"}
                  data-plasmic-override={overrides.image26}
                  className={classNames(projectcss.all, sty.image26)}
                />

                <div
                  data-plasmic-name={"image30"}
                  data-plasmic-override={overrides.image30}
                  className={classNames(projectcss.all, sty.image30)}
                />
              </div>

              <Rectangle13Icon
                className={classNames(projectcss.all, sty.svg__nyLpe)}
                role={"img"}
              />

              <p.PlasmicImg
                data-plasmic-name={"img"}
                data-plasmic-override={overrides.img}
                alt={""}
                className={classNames(sty.img)}
                displayHeight={"25.351px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"82.02px"}
                loading={"lazy"}
                src={{
                  src: airbnb13XfvUa0Ouk,
                  fullWidth: 82.02,
                  fullHeight: 25.351,
                  aspectRatio: 3.192308
                }}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__gh05C
                )}
              >
                {"Online Experiences"}
              </div>

              <div
                data-plasmic-name={
                  "joinUniqueInteractiveActivitiesLedByOneOfAKindHostsallWithoutLeavingHome"
                }
                data-plasmic-override={
                  overrides.joinUniqueInteractiveActivitiesLedByOneOfAKindHostsallWithoutLeavingHome
                }
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.joinUniqueInteractiveActivitiesLedByOneOfAKindHostsallWithoutLeavingHome
                )}
              >
                {
                  "Join unique interactive activities led by one-of-a-kind hosts—all without leaving home.\r\n"
                }
              </div>

              <div
                data-plasmic-name={"group65"}
                data-plasmic-override={overrides.group65}
                className={classNames(projectcss.all, sty.group65)}
              >
                <div
                  data-plasmic-name={"lifeLessonsWithKatieZaferes"}
                  data-plasmic-override={overrides.lifeLessonsWithKatieZaferes}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.lifeLessonsWithKatieZaferes
                  )}
                >
                  {"Life lessons with Katie Zaferes\n"}
                </div>

                <div
                  data-plasmic-name={"from136Person"}
                  data-plasmic-override={overrides.from136Person}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.from136Person
                  )}
                >
                  {"From $136 / person\n"}
                </div>

                <div
                  data-plasmic-name={"_50"}
                  data-plasmic-override={overrides._50}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty._50
                  )}
                >
                  {"5.0\n"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___7HOlS
                  )}
                >
                  {"(6)"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__idw22
                  )}
                >
                  {"USA"}
                </div>

                <Star1Icon
                  className={classNames(projectcss.all, sty.svg__nvnlK)}
                  role={"img"}
                />

                <Ellipse6Icon
                  className={classNames(projectcss.all, sty.svg__oExh)}
                  role={"img"}
                />
              </div>

              <div
                data-plasmic-name={"group78"}
                data-plasmic-override={overrides.group78}
                className={classNames(projectcss.all, sty.group78)}
              >
                <div
                  data-plasmic-name={"learnWeddingPhotography"}
                  data-plasmic-override={overrides.learnWeddingPhotography}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.learnWeddingPhotography
                  )}
                >
                  {"Learn wedding photography\n"}
                </div>

                <div
                  data-plasmic-name={"from125Person"}
                  data-plasmic-override={overrides.from125Person}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.from125Person
                  )}
                >
                  {"From $125 / person\n"}
                </div>

                <div
                  data-plasmic-name={"_6"}
                  data-plasmic-override={overrides._6}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty._6
                  )}
                >
                  {"5.0\n"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___4Wm3U
                  )}
                >
                  {"(30)"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__wnHQe
                  )}
                >
                  {"USA"}
                </div>

                <Star1Icon
                  className={classNames(projectcss.all, sty.svg__ulkIy)}
                  role={"img"}
                />

                <Ellipse6Icon
                  className={classNames(projectcss.all, sty.svg___46Joo)}
                  role={"img"}
                />
              </div>

              <div
                data-plasmic-name={"group79"}
                data-plasmic-override={overrides.group79}
                className={classNames(projectcss.all, sty.group79)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__rpp4O
                  )}
                >
                  {"Group Mountain Biking"}
                </div>

                <div
                  data-plasmic-name={"from50Person"}
                  data-plasmic-override={overrides.from50Person}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.from50Person
                  )}
                >
                  {"From $50 / person\n"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___28Okz
                  )}
                >
                  {"4.8"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__nsQCn
                  )}
                >
                  {"(2)"}
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__v1L85
                  )}
                >
                  {"USA"}
                </div>

                <Star1Icon
                  className={classNames(projectcss.all, sty.svg__m3MN)}
                  role={"img"}
                />

                <Ellipse6Icon
                  className={classNames(projectcss.all, sty.svg__mBqUb)}
                  role={"img"}
                />
              </div>

              <div
                data-plasmic-name={"image12"}
                data-plasmic-override={overrides.image12}
                className={classNames(projectcss.all, sty.image12)}
              />

              <div
                data-plasmic-name={"group80"}
                data-plasmic-override={overrides.group80}
                className={classNames(projectcss.all, sty.group80)}
              >
                <div
                  data-plasmic-name={"rectangle41"}
                  data-plasmic-override={overrides.rectangle41}
                  className={classNames(projectcss.all, sty.rectangle41)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__cPi1C
                  )}
                >
                  {"SOLD OUT"}
                </div>
              </div>

              <div
                data-plasmic-name={"group72"}
                data-plasmic-override={overrides.group72}
                className={classNames(projectcss.all, sty.group72)}
              >
                <div
                  data-plasmic-name={
                    "furtherDescriptionsAboutLifeLessonsWithKatieZaferes"
                  }
                  data-plasmic-override={
                    overrides.furtherDescriptionsAboutLifeLessonsWithKatieZaferes
                  }
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.furtherDescriptionsAboutLifeLessonsWithKatieZaferes
                  )}
                >
                  {
                    "Further descriptions about Life lessons with Katie Zaferes\n"
                  }
                </div>
              </div>

              <div
                data-plasmic-name={"weddingPhotography1"}
                data-plasmic-override={overrides.weddingPhotography1}
                className={classNames(projectcss.all, sty.weddingPhotography1)}
              />

              <div
                data-plasmic-name={"mountainBike1"}
                data-plasmic-override={overrides.mountainBike1}
                className={classNames(projectcss.all, sty.mountainBike1)}
              />

              <div
                data-plasmic-name={"group81"}
                data-plasmic-override={overrides.group81}
                className={classNames(projectcss.all, sty.group81)}
              >
                <div
                  data-plasmic-name={"rectangle42"}
                  data-plasmic-override={overrides.rectangle42}
                  className={classNames(projectcss.all, sty.rectangle42)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__aViaK
                  )}
                >
                  {"ONLINE"}
                </div>
              </div>
            </div>
          </div>
        ) : null}
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "airBnbExperiences",
    "group77",
    "image28",
    "image29",
    "image25",
    "image22",
    "image23",
    "image24",
    "image27",
    "image26",
    "image30",
    "img",
    "joinUniqueInteractiveActivitiesLedByOneOfAKindHostsallWithoutLeavingHome",
    "group65",
    "lifeLessonsWithKatieZaferes",
    "from136Person",
    "_50",
    "group78",
    "learnWeddingPhotography",
    "from125Person",
    "_6",
    "group79",
    "from50Person",
    "image12",
    "group80",
    "rectangle41",
    "group72",
    "furtherDescriptionsAboutLifeLessonsWithKatieZaferes",
    "weddingPhotography1",
    "mountainBike1",
    "group81",
    "rectangle42"
  ],

  airBnbExperiences: [
    "airBnbExperiences",
    "group77",
    "image28",
    "image29",
    "image25",
    "image22",
    "image23",
    "image24",
    "image27",
    "image26",
    "image30",
    "img",
    "joinUniqueInteractiveActivitiesLedByOneOfAKindHostsallWithoutLeavingHome",
    "group65",
    "lifeLessonsWithKatieZaferes",
    "from136Person",
    "_50",
    "group78",
    "learnWeddingPhotography",
    "from125Person",
    "_6",
    "group79",
    "from50Person",
    "image12",
    "group80",
    "rectangle41",
    "group72",
    "furtherDescriptionsAboutLifeLessonsWithKatieZaferes",
    "weddingPhotography1",
    "mountainBike1",
    "group81",
    "rectangle42"
  ],

  group77: [
    "group77",
    "image28",
    "image29",
    "image25",
    "image22",
    "image23",
    "image24",
    "image27",
    "image26",
    "image30"
  ],

  image28: ["image28"],
  image29: ["image29"],
  image25: ["image25"],
  image22: ["image22"],
  image23: ["image23"],
  image24: ["image24"],
  image27: ["image27"],
  image26: ["image26"],
  image30: ["image30"],
  img: ["img"],
  joinUniqueInteractiveActivitiesLedByOneOfAKindHostsallWithoutLeavingHome: [
    "joinUniqueInteractiveActivitiesLedByOneOfAKindHostsallWithoutLeavingHome"
  ],

  group65: ["group65", "lifeLessonsWithKatieZaferes", "from136Person", "_50"],
  lifeLessonsWithKatieZaferes: ["lifeLessonsWithKatieZaferes"],
  from136Person: ["from136Person"],
  _50: ["_50"],
  group78: ["group78", "learnWeddingPhotography", "from125Person", "_6"],
  learnWeddingPhotography: ["learnWeddingPhotography"],
  from125Person: ["from125Person"],
  _6: ["_6"],
  group79: ["group79", "from50Person"],
  from50Person: ["from50Person"],
  image12: ["image12"],
  group80: ["group80", "rectangle41"],
  rectangle41: ["rectangle41"],
  group72: ["group72", "furtherDescriptionsAboutLifeLessonsWithKatieZaferes"],
  furtherDescriptionsAboutLifeLessonsWithKatieZaferes: [
    "furtherDescriptionsAboutLifeLessonsWithKatieZaferes"
  ],

  weddingPhotography1: ["weddingPhotography1"],
  mountainBike1: ["mountainBike1"],
  group81: ["group81", "rectangle42"],
  rectangle42: ["rectangle42"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    airBnbExperiences: makeNodeComponent("airBnbExperiences"),
    group77: makeNodeComponent("group77"),
    image28: makeNodeComponent("image28"),
    image29: makeNodeComponent("image29"),
    image25: makeNodeComponent("image25"),
    image22: makeNodeComponent("image22"),
    image23: makeNodeComponent("image23"),
    image24: makeNodeComponent("image24"),
    image27: makeNodeComponent("image27"),
    image26: makeNodeComponent("image26"),
    image30: makeNodeComponent("image30"),
    img: makeNodeComponent("img"),
    joinUniqueInteractiveActivitiesLedByOneOfAKindHostsallWithoutLeavingHome:
      makeNodeComponent(
        "joinUniqueInteractiveActivitiesLedByOneOfAKindHostsallWithoutLeavingHome"
      ),

    group65: makeNodeComponent("group65"),
    lifeLessonsWithKatieZaferes: makeNodeComponent(
      "lifeLessonsWithKatieZaferes"
    ),

    from136Person: makeNodeComponent("from136Person"),
    _50: makeNodeComponent("_50"),
    group78: makeNodeComponent("group78"),
    learnWeddingPhotography: makeNodeComponent("learnWeddingPhotography"),
    from125Person: makeNodeComponent("from125Person"),
    _6: makeNodeComponent("_6"),
    group79: makeNodeComponent("group79"),
    from50Person: makeNodeComponent("from50Person"),
    image12: makeNodeComponent("image12"),
    group80: makeNodeComponent("group80"),
    rectangle41: makeNodeComponent("rectangle41"),
    group72: makeNodeComponent("group72"),
    furtherDescriptionsAboutLifeLessonsWithKatieZaferes: makeNodeComponent(
      "furtherDescriptionsAboutLifeLessonsWithKatieZaferes"
    ),

    weddingPhotography1: makeNodeComponent("weddingPhotography1"),
    mountainBike1: makeNodeComponent("mountainBike1"),
    group81: makeNodeComponent("group81"),
    rectangle42: makeNodeComponent("rectangle42"),
    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
